openapi: '3.0.0'
info:
  title: Book Publishing Service
  description: Spring Boot application for managing a book publishing house. This service exposes a REST API that supports managing authors and publishing books as well as exposing them to the public.
  version: '1.0.0'
security:
  - BarerAuth: [ ]
paths:

  /authors:
    get:
      summary: Get all authors
      tags:
        - Author
      operationId: getAllAuthors
      responses:
        '200':
          description: 'List of authors'
          content:
            application/json:
              example:
                - $ref: '#/components/examples/AuthorList/value'
    post:
      summary: Add an Author
      tags:
        - Authors
      description: Add a new Author
      operationId: saveAuthor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  readOnly: true
                surname:
                  type: string
                  readOnly: true
      responses:
        '201':
          description: Author successfully created
  /authors/{id}:
    put:
      summary: Update Author
      tags:
        - Authors
      operationId: updateAuthor
      description: Update Author whose id is provided
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  readOnly: true
                surname:
                  type: string
                  readOnly: true
      responses:
        '200':
          description: Author successfully updated
  /books:
    get:
      summary: Get all books
      tags:
        - Books
      operationId: getAllBooks
      responses:
        '200':
          description: List of books
    post:
      summary: Publish a book
      tags:
        - Books
      operationId: saveBook
      description: Publish a new book
      responses:
        '201':
          description: New book created
